# Generated by Django 5.0.3 on 2025-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_table_billitems_total_km_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voucherconfiguration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="voucherconfiguration",
            name="fy_year",
            field=models.CharField(default="2025-2026", max_length=100),
        ),
        migrations.AlterField(
            model_name="voucherconfiguration",
            name="category",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt"),
                    ("payment", "Payment"),
                    ("Debit Note", "Debit Note"),
                    ("Credit Note", "Credit Note"),
                    ("Contra Entry", "Contra Entry"),
                    ("Journal Entry", "Journal Entry"),
                    ("Trip sheet", "Trip sheet"),
                    ("Sales", "Sales"),
                    ("Service Voucher", "Service Voucher"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherconfiguration",
            constraint=models.UniqueConstraint(
                fields=("company", "branch", "category", "series", "fy_year"),
                name="unique_company_branch_category_series_fy_year",
            ),
        ),
    ]
