# Generated by Django 5.0.3 on 2025-09-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_voucherconfiguration_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("sub_group", models.CharField(max_length=100)),
                ("reorder", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
                ("min_level", models.IntegerField()),
                ("godown", models.CharField(max_length=100)),
                ("hsn", models.CharField(max_length=100)),
                ("max_level", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("co_id", models.CharField(default="c", max_length=10)),
                ("branch_id", models.CharField(default="branch", max_length=50)),
                (
                    "financial_year",
                    models.CharField(default="2024-2025", max_length=10),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.groupmaster",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.unitmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.IntegerField(blank=True, null=True)),
                ("p_price", models.FloatField(blank=True, default=0.0, null=True)),
                ("land_coast", models.FloatField(blank=True, default=0.0, null=True)),
                ("price_1", models.FloatField(blank=True, default=0.0, null=True)),
                ("price_2", models.FloatField(blank=True, default=0.0, null=True)),
                ("price_3", models.FloatField(blank=True, default=0.0, null=True)),
                ("mrp", models.FloatField(blank=True, default=0.0, null=True)),
                ("tax_code", models.CharField(max_length=100)),
                ("op_stock", models.FloatField(blank=True, default=0.0, null=True)),
                ("op_lc", models.FloatField(blank=True, default=0.0, null=True)),
                ("stock", models.FloatField(blank=True, default=0.0, null=True)),
                ("batch_no", models.CharField(max_length=200)),
                ("exp_date", models.DateField()),
                ("co_id", models.CharField(default="c", max_length=10)),
                ("branch_id", models.CharField(default="branch", max_length=50)),
                (
                    "financial_year",
                    models.CharField(default="2024-2025", max_length=10),
                ),
                (
                    "gst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.taxmaster",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.item_master",
                    ),
                ),
            ],
        ),
    ]
