# Generated by Django 5.0.3 on 2025-09-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_locationmaster_vendormaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branch_master",
            ),
        ),
    ]
