# Generated by Django 5.0.3 on 2025-09-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_taxmaster_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branch_master",
            ),
        ),
        migrations.AddField(
            model_name="groupmaster",
            name="fy_code",
            field=models.CharField(default="2025-2026", max_length=15),
        ),
        migrations.AddField(
            model_name="unitmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branch_master",
            ),
        ),
        migrations.AddField(
            model_name="unitmaster",
            name="fy_code",
            field=models.CharField(default="2025-2026", max_length=15),
        ),
    ]
