# Generated by Django 5.0.3 on 2025-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_groupmaster_branch_groupmaster_fy_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmaster",
            name="customer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
