# Generated by Django 5.0.3 on 2025-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_locationmaster_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip_sheet",
            name="fuel_station",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
