# Generated by Django 5.0.3 on 2025-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_trip_sheet_fuel_station"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table_billitems",
            name="code",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="ehr_rate",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="fixed_charge",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="gross_amount",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="haulting",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="monthly_fixed_charge",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="net_value",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="table_billitems",
            name="trip",
        ),
        migrations.RemoveField(
            model_name="table_billmaster",
            name="additional_charges",
        ),
        migrations.RemoveField(
            model_name="table_billmaster",
            name="total_km",
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="additional_charge",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="additional_km",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="fixed_km",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="fixed_or_rental_charge",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table_billitems",
            name="total_charges",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
