# Generated by Django 5.0.3 on 2025-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_remove_table_billitems_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratechild",
            name="km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
