# Generated by Django 5.0.3 on 2025-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_ratechild_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee_master",
            name="additional_charge",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee_master",
            name="fixed_charge",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee_master",
            name="fixed_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee_master",
            name="km_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
