# Generated by Django 4.2 on 2025-11-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_employee_master_additional_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='category',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note'), ('Contra Entry', 'Contra Entry'), ('Journal Entry', 'Journal Entry'), ('Trip sheet', 'Trip sheet'), ('Sales', 'Sales'), ('Lorry Receipt', 'Lorry Receipt'), ('Service Voucher', 'Service Voucher')], max_length=255),
        ),
    ]
