# Generated by Django 4.2 on 2025-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_voucherconfiguration_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmaster',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='locationmaster',
            name='loading_point',
        ),
        migrations.RemoveField(
            model_name='locationmaster',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='locationmaster',
            name='unloading_point',
        ),
        migrations.RemoveField(
            model_name='locationmaster',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
