# Generated by Django 4.2 on 2025-11-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_locationmaster_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryReceiptMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(default='2025-2026', max_length=15)),
                ('lr_no', models.PositiveIntegerField()),
                ('lr_date', models.DateField()),
                ('consigner_name', models.CharField(max_length=200)),
                ('consigner_code', models.IntegerField()),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_code', models.IntegerField()),
                ('payment', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=80)),
                ('load_from', models.CharField(max_length=100)),
                ('load_to', models.CharField(max_length=100)),
                ('total_charges', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
                ('consignee_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignee_accounts', to='main.table_accountsmaster')),
                ('consigner_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consigner_accounts', to='main.table_accountsmaster')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucherconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='LorryReceiptItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('freight', models.FloatField()),
                ('pkg', models.CharField(max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lorryreceiptmaster')),
            ],
        ),
    ]
