# Generated by Django 4.2 on 2025-11-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_lorryreceiptmaster_lorryreceiptitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
            ],
        ),
    ]
