# Generated by Django 4.2 on 2025-11-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_areamaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
