# Generated by Django 4.2 on 2025-11-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_lorryreceiptmaster_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorryreceiptmaster',
            name='invoice_date',
        ),
    ]
