# Generated by Django 4.2 on 2025-11-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_lorryreceiptmaster_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorryreceiptmaster',
            name='invoice_no',
        ),
    ]
