# Generated by Django 4.2 on 2025-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_lorryreceiptmaster_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='inv_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='inv_no',
            field=models.CharField(default='00120', max_length=255),
        ),
    ]
