# Generated by Django 4.2 on 2025-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_lorryreceiptitems_inv_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorryreceiptitems',
            name='inv_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lorryreceiptitems',
            name='inv_no',
            field=models.CharField(max_length=255),
        ),
    ]
