# Generated by Django 4.2 on 2025-11-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_lorryreceiptitems_inv_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_master',
            name='chase_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_master',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_master',
            name='make_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
