# Generated by Django 4.2 on 2025-11-18 05:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_vehicle_master_chase_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratechild',
            old_name='vehicle',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='ratechild',
            name='additional_charge',
        ),
        migrations.RemoveField(
            model_name='ratechild',
            name='fixed_rate',
        ),
        migrations.RemoveField(
            model_name='ratechild',
            name='km',
        ),
        migrations.RemoveField(
            model_name='ratechild',
            name='type',
        ),
        migrations.AlterField(
            model_name='vehicle_master',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
