# Generated by Django 4.2 on 2025-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_vehicle_ratechild_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratechild',
            name='rate',
            field=models.FloatField(),
        ),
    ]
