# Generated by Django 4.2 on 2025-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_ratechild_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='district',
            field=models.CharField(default='KOLLAM', max_length=150),
            preserve_default=False,
        ),
    ]
