# Generated by Django 4.2 on 2025-11-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_lorryreceiptmaster_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorryreceiptmaster',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
