# Generated by Django 4.2 on 2025-11-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_lorryreceiptmaster_vehicle_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
