# Generated by Django 4.2 on 2025-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_lorryreceiptmaster_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorryreceiptmaster',
            name='checked',
        ),
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
