# Generated by Django 4.2 on 2025-12-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_lorryreceiptmaster_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorryreceiptmaster',
            name='area',
        ),
        migrations.RemoveField(
            model_name='lorryreceiptmaster',
            name='district',
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='door_cl_dl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='gross_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='hamali',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='risk_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='statutory_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
