# Generated by Django 4.2 on 2025-12-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_lorryreceiptmaster_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table_accountsmaster',
            unique_together={('branch', 'head')},
        ),
    ]
