# Generated by Django 4.2 on 2025-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_table_accountsmaster_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='branch_to',
            field=models.CharField(default='TRIVANDRUM', max_length=100),
        ),
    ]
