# Generated by Django 4.2 on 2025-12-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_lorryreceiptmaster_branch_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(default='2025-2026', max_length=15)),
                ('receipt_no', models.PositiveIntegerField()),
                ('receipt_date', models.DateField()),
                ('consigner_name', models.CharField(max_length=200)),
                ('consigner_code', models.IntegerField()),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_code', models.IntegerField()),
                ('payment', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(blank=True, max_length=80, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('load_from', models.CharField(max_length=100)),
                ('load_to', models.CharField(max_length=100)),
                ('hamali', models.FloatField(default=0.0)),
                ('door_cl_dl', models.FloatField(default=0.0)),
                ('risk_charge', models.FloatField(default=0.0)),
                ('statutory_charge', models.FloatField(default=0.0)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('total_charges', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
                ('consignee_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_consignee_accounts', to='main.table_accountsmaster')),
                ('consigner_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_consigner_accounts', to='main.table_accountsmaster')),
                ('lr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lorryreceiptmaster')),
            ],
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='category',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note'), ('Contra Entry', 'Contra Entry'), ('Journal Entry', 'Journal Entry'), ('Trip sheet', 'Trip sheet'), ('Sales', 'Sales'), ('Lorry Receipt', 'Lorry Receipt'), ('Cash Receipt', 'Cash Receipt'), ('Service Voucher', 'Service Voucher')], max_length=255),
        ),
        migrations.CreateModel(
            name='CashReceiptItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('inv_no', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('inv_amount', models.FloatField()),
                ('freight', models.FloatField()),
                ('pkg', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cashreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucherconfiguration'),
        ),
    ]
