# Generated by Django 4.2 on 2025-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_cashreceipt_alter_voucherconfiguration_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceiptitems',
            name='checked',
        ),
    ]
