# Generated by Django 4.2 on 2025-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_cashreceiptitems_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
