# Generated by Django 4.2 on 2025-12-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_voucherconfiguration_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDespatchMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(default='2025-2026', max_length=15)),
                ('gdm_no', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('branch_to', models.CharField(max_length=80)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('driver_name', models.CharField(max_length=125)),
                ('grand_total', models.FloatField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucherconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='GDMChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_date', models.DateField()),
                ('lr_no', models.PositiveIntegerField()),
                ('load_from', models.CharField(max_length=255)),
                ('load_to', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=30)),
                ('inv_no', models.CharField(max_length=85)),
                ('item', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('pkg', models.CharField(max_length=155)),
                ('freight', models.FloatField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goodsdespatchmemo')),
            ],
        ),
    ]
