# Generated by Django 4.2 on 2025-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_goodsdespatchmemo_gdmchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdmchild',
            name='inv_amount',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
