# Generated by Django 4.2 on 2025-12-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_gdmchild_inv_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdmchild',
            name='lr_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lorryreceiptitems'),
        ),
    ]
