# Generated by Django 4.2 on 2025-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_gdmchild_lr_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='category',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note'), ('Contra Entry', 'Contra Entry'), ('Journal Entry', 'Journal Entry'), ('Trip sheet', 'Trip sheet'), ('Sales', 'Sales'), ('Lorry Receipt', 'Lorry Receipt'), ('Lorry Hire', 'Lorry Hire'), ('GDM', 'GDM'), ('Cash Receipt', 'Cash Receipt'), ('Service Voucher', 'Service Voucher')], max_length=255),
        ),
    ]
