# Generated by Django 4.2 on 2025-12-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_voucherconfiguration_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(default='2025-2026', max_length=15)),
                ('memo_no', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('to', models.CharField(max_length=255)),
                ('load_from', models.CharField(max_length=255)),
                ('load_to', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=100)),
                ('lorry_no', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(max_length=50)),
                ('dl_no', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('product', models.CharField(max_length=100)),
                ('loading_coolie', models.FloatField()),
                ('lorry_hire', models.FloatField()),
                ('advance', models.FloatField()),
                ('balance', models.FloatField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucherconfiguration')),
            ],
        ),
    ]
