# Generated by Django 4.2 on 2025-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_lorryhire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorryhire',
            name='advance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='dl_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='loading_coolie',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='lorry_hire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='transport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
