# Generated by Django 4.2 on 2025-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_lorryhire_advance_alter_lorryhire_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='charged_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lorryreceiptitems',
            name='numbers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='casual_leaves',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
