# Generated by Django 4.2 on 2025-12-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_lorryreceiptitems_charged_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='eway_billno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
