# Generated by Django 4.2 on 2025-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_lorryreceiptmaster_eway_billno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='cr_door_cl_dl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cr_hamali',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cr_risk_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='cr_statutory_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
