# Generated by Django 4.2 on 2025-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_cashreceipt_cr_door_cl_dl_cashreceipt_cr_hamali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceiptitems',
            name='charged_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashreceiptitems',
            name='numbers',
            field=models.IntegerField(default=1),
        ),
    ]
