# Generated by Django 4.2 on 2025-12-31 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_cashreceiptitems_charged_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee_master'),
        ),
    ]
