# Generated by Django 4.2 on 2026-01-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_cashreceipt_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='consignee_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
