# Generated by Django 4.2 on 2026-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_lorryreceiptmaster_consignee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdmchild',
            name='charged_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
