# Generated by Django 4.2 on 2026-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_gdmchild_charged_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='invoice_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lorryreceiptmaster',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
