# Generated by Django 4.2 on 2026-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_lorryreceiptmaster_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_companydetailsmaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
