# Generated by Django 4.2 on 2026-01-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_table_companydetailsmaster_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdespatchmemo',
            name='driver_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
